name: nice-html
version: '0.1.0.0'
category: Web
author: Mike Ledger
maintainer: mike@quasimal.com
copyright: 2017 Mike Ledger
license: MIT
github: mikeplus64/nice-html
extra-source-files:
- README.md

ghc-options: -Wall -O2

library:
  source-dirs: src
  exposed-modules:
  - Text.Html.Nice
  - Text.Html.Nice.Internal
  - Text.Html.Nice.FreeMonad
  - Text.Html.Nice.Writer
  - Text.Html.Nice.Writer.Html5
  dependencies:
  - base >=4.7 && <5
  - bytestring
  - deepseq
  - text >=1.2
  - lens
  - vector
  - template-haskell
  - blaze-html
  - blaze-markup
  - recursion-schemes
  - transformers
  - free
  - bifunctors
  - data-default-class
  - pretty-show

_benchmarks: &bench-opts
  dependencies:
  - base
  - criterion
  - blaze-markup
  - blaze-html
  - lucid
  - text
  - bytestring
  - nice-html
  - weigh
  - pretty-show
  other-modules:
  - BigTable.Blaze
  - BigTable.Lucid
  - BigTable.Nice
  source-dirs: benchmarks

benchmarks:
  perf:
    <<: *bench-opts
    main: Perf.hs

  mem:
    <<: *bench-opts
    main: Mem.hs
