name: nice-html
version: '0.1.0.0'
category: Web
author: Mike Ledger
maintainer: mike@quasimal.com
copyright: 2017 Mike Ledger
license: MIT
github: mikeplus64/nice-html
extra-source-files:
- README.md

library:
  source-dirs: src
  exposed-modules:
  - Text.Html.Nice
  - Text.Html.Nice.Monad
  dependencies:
  - base >=4.7 && <5
  - text >=1.2
  - containers
  - lens
  - vector
  - template-haskell
  - blaze-html
  - blaze-markup
  - recursion-schemes
  - transformers
  - free
  - bifunctors
  - data-default-class

benchmarks:
  bigtable:
    main: BigTable.hs
    source-dirs: benchmarks
    other-modules:
    - BigTable.Blaze
    - BigTable.Lucid
    - BigTable.Nice
    dependencies:
    - base
    - criterion
    - blaze-markup
    - blaze-html
    - lucid
    - text
    - bytestring
    - nice-html
